### ISSUE TITLE
Sending domain sandbox option mismatch when using "testing@sparkpostbox.com"

### ISSUE THREAD

**Issue by Kiran-N** [SparkPost/sparkpost-api-documentation#34]
I am using the spark post addon in heroku. I dont know why I am not able to test sending the emails using the sparkpostbox.com

		    ```
    Client client = new Client(API_KEY);
		        try {
					client.sendMessage(
					        "testing@sparkpostbox.com",
					        "myemail@abc.com",
					        "The subject of the message",
					        "The text part of the email",
					        "<b>The HTML part of the email</b>");
				} catch (SparkPostException e) {
					throw e;
				}
```

ERROR:

{ "errors": [ { "message": "Message generation rejected", "description": "Sending domain sandbox option mismatch", "code": "1902" } ], "results": { "total_rejected_recipients": 0, "total_accepted_recipients": 1, "id": "48505117442189718" } }

**Comment by ewandennis** [comment]
Thanks for the report @Kiran-N. There's a patch coming for [java-sparkpost](https://github.com/SparkPost/java-sparkpost/pull/55) to address this issue. You can [track the issue here](https://github.com/SparkPost/java-sparkpost/issues/54) but, to unstick you in the meantime, you could send a transmission directly using the full SparkPost API by following [this example](https://github.com/SparkPost/java-sparkpost/blob/master/apps/sparkpost-samples-app/src/main/java/com/sparkpost/samples/SendEmailSample.java).

If you choose to send from `@sparkpostbox.com`, you will also have to set the sandbox option on your transmission like this:

```java
OptionsAttributes options = new OptionsAttributes();
options.setSandbox(true);
transmission.setOptions(options);
```

I hope this helps. I'm going to close this issue in favour of [the one on java-sparkpost](https://github.com/SparkPost/java-sparkpost/issues/54).
